### ISSUE TITLE
RuntimeError: IOLoop is already running

### ISSUE THREAD

**Issue by kingname** [littlecodersh/trip#11]
In Jupyter, this error will always be raised. but the result can be gotten though.

**Comment by littlecodersh** [comment]
@kingname I think it may be caused by Jupyter.
Because from the printed result, we find out that the first `start` is finished successfully while it's nowhere called again. 
I have never tried Jupyter, so I'm sorry I am not able to help.

p.s. next time, remember to cover your ip address :smile:

**Comment by kingname** [comment]
Nice shot, I have already removed the image. I think the problem is that jupyter is just like python's origin interactive environment (type `python3` and then enter in terminal). and I can not start the IOLoop twice (something like asyncio's eventloop, you could not open eventloop twice).

Therefore, I think you should try to run your example just in python's interactive environment, and you will find the problem occur again.

**Comment by littlecodersh** [comment]
@kingname I tried but failed to reproduce your error.
Will you please give me your Python version and system version?

![1513284348](https://user-images.githubusercontent.com/13028340/34013555-dd513286-e152-11e7-9cf2-554ec9ea9497.png)

**Comment by harveyqiu** [comment]
I had the same problem when I run this program on my Windows with py3.6.0

**Comment by canwushuang** [comment]
有同样的问题。如创建一个爬取代理并验证的协程以及一个更换代理爬取网页的协程，两者不能很好的并存。求教
