### ISSUE TITLE
请问有没有和grequests的对比呢？

### ISSUE THREAD

**Issue by franklingu** [littlecodersh/trip#5]
如题

 grequests 是requests + gevent， requests的作者写的，也很简短

可以和aiohttp比较吗？

可以对比速度，易用性，功能丰富程度等

**Comment by littlecodersh** [comment]
@franklingu 目前没有这个打算。
比较免不了贬低别的框架，我又觉得别的框架都写的很好不想贬低，所以就没有这个打算了。
我更倾向于发现一些别的框架做的很好的点，看看我能不能做些改进。
所以有建议的话非常欢迎和我提，或者加群交流。
